/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author a1294121
 */
public class Visao extends javax.swing.JFrame {

    /**
     * Creates new form Visao
     */
    public Visao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Cliente = new javax.swing.JMenu();
        jMenuItemClienteCadastrar = new javax.swing.JMenuItem();
        jMenuItemClienteAlterar = new javax.swing.JMenuItem();
        jMenuItemClienteExcluir = new javax.swing.JMenuItem();
        jMenuItemClienteConsultar = new javax.swing.JMenuItem();
        jMenu2Produto = new javax.swing.JMenu();
        jMenuItemProdutoCadastro = new javax.swing.JMenuItem();
        jMenuItemProdutoAlterar = new javax.swing.JMenuItem();
        jMenuItemProdutoExcluir = new javax.swing.JMenuItem();
        jMenuItemProdutoConsultar = new javax.swing.JMenuItem();
        jMenu6Creditar = new javax.swing.JMenu();
        jMenu7Debitar = new javax.swing.JMenu();
        jMenu1Ajuda = new javax.swing.JMenu();
        jMenu2Sobre = new javax.swing.JMenu();

        jButton3.setText("jButton3");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartão Universitário", 0, 0, new java.awt.Font("Dialog", 1, 18), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341100_shopping_cart.png"))); // NOI18N
        jButton1.setToolTipText("Debitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341006_client.png"))); // NOI18N
        jToggleButton1.setToolTipText("Cliente");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373340942_03.png"))); // NOI18N
        jToggleButton2.setToolTipText("Creditar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("Consulta por Nome");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341694_search_magnifying_glass_find.png"))); // NOI18N
        jButton2.setToolTipText("Pesquisa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/a1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(103, 103, 103))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusLost(evt);
            }
        });

        jMenu1Cliente.setText("Cliente");

        jMenuItemClienteCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980201_executive.png"))); // NOI18N
        jMenuItemClienteCadastrar.setText("Cadastrar");
        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastrarActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteCadastrar);

        jMenuItemClienteAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980328_121.png"))); // NOI18N
        jMenuItemClienteAlterar.setText("Alterar");
        jMenuItemClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteAlterarActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteAlterar);

        jMenuItemClienteExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980249_delete.png"))); // NOI18N
        jMenuItemClienteExcluir.setText("Excluir");
        jMenuItemClienteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteExcluirActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteExcluir);

        jMenuItemClienteConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980081_find.png"))); // NOI18N
        jMenuItemClienteConsultar.setText("Consultar");
        jMenuItemClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteConsultarActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteConsultar);

        jMenuBar1.add(jMenu1Cliente);

        jMenu2Produto.setText("Produto");

        jMenuItemProdutoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375981249_product.png"))); // NOI18N
        jMenuItemProdutoCadastro.setText("Cadastrar");
        jMenuItemProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoCadastroActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoCadastro);

        jMenuItemProdutoAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980328_121.png"))); // NOI18N
        jMenuItemProdutoAlterar.setText("Alterar");
        jMenuItemProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoAlterarActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoAlterar);

        jMenuItemProdutoExcluir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980249_delete.png"))); // NOI18N
        jMenuItemProdutoExcluir.setText("Excluir");
        jMenuItemProdutoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoExcluirActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoExcluir);

        jMenuItemProdutoConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980081_find.png"))); // NOI18N
        jMenuItemProdutoConsultar.setText("Consultar");
        jMenuItemProdutoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoConsultarActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoConsultar);

        jMenuBar1.add(jMenu2Produto);

        jMenu6Creditar.setText("Creditar");
        jMenu6Creditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6CreditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6Creditar);

        jMenu7Debitar.setText("Debitar");
        jMenu7Debitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7DebitarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7Debitar);

        jMenu1Ajuda.setText("Ajuda");
        jMenu1Ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1AjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1Ajuda);

        jMenu2Sobre.setText("Sobre");
        jMenu2Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2SobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2Sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Debitar d = new Debitar();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        Cliente c = new Cliente(this);
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        Credito s = new Credito();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Consulta q = new Consulta();
        q.setVisible(true);
        q.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItemClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteAlterarActionPerformed

    private void jMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1FocusGained

    private void jMenuBar1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1FocusLost

    private void jMenuItemClienteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteExcluirActionPerformed

    private void jMenuItemClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastrarActionPerformed
        this.setEnabled(false);
        Cliente c = new Cliente(this);
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemClienteCadastrarActionPerformed

    private void jMenuItemProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProdutoAlterarActionPerformed

    private void jMenuItemProdutoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProdutoExcluirActionPerformed

    private void jMenuItemProdutoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProdutoConsultarActionPerformed

    private void jMenuItemClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteConsultarActionPerformed

    private void jMenuItemProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoCadastroActionPerformed
        this.setEnabled(false);
        CadastroProduto l = new CadastroProduto(this);
        l.setVisible(true);
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemProdutoCadastroActionPerformed

    private void jMenu1AjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1AjudaMouseClicked
        Desktop desktop = null;
        desktop = Desktop.getDesktop();
        URI uri = null;
        try {
            String local = System.getProperty("user.dir"); 
            //uri = new URI("file:///home/todos/alunos/cm/a1294121/%C3%81rea%20de%20Trabalho/Projeto/Site/Help.xhtml");
            uri = new URI("file://"+local+"/Site/Help.xhtml");
            desktop.browse(uri);
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (URISyntaxException use) {
            use.printStackTrace();
        }                            
    }//GEN-LAST:event_jMenu1AjudaMouseClicked

    private void jMenu2SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2SobreMouseClicked
        Sobre w = new Sobre();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu2SobreMouseClicked

    private void jMenu6CreditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6CreditarMouseClicked
       Credito s = new Credito();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu6CreditarMouseClicked

    private void jMenu7DebitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7DebitarMouseClicked
        Debitar d = new Debitar();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu7DebitarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Visao v = new Visao();
                v.setVisible(true);
                v.setLocationRelativeTo(null);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1Ajuda;
    private javax.swing.JMenu jMenu1Cliente;
    private javax.swing.JMenu jMenu2Produto;
    private javax.swing.JMenu jMenu2Sobre;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6Creditar;
    private javax.swing.JMenu jMenu7Debitar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemClienteAlterar;
    private javax.swing.JMenuItem jMenuItemClienteCadastrar;
    private javax.swing.JMenuItem jMenuItemClienteConsultar;
    private javax.swing.JMenuItem jMenuItemClienteExcluir;
    private javax.swing.JMenuItem jMenuItemProdutoAlterar;
    private javax.swing.JMenuItem jMenuItemProdutoCadastro;
    private javax.swing.JMenuItem jMenuItemProdutoConsultar;
    private javax.swing.JMenuItem jMenuItemProdutoExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
