/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBConnection;
import Model.DaoCategoria;
import Model.HibernateDao;
import entities.Categoria;
import entities.Pessoa;
import entities.Produto;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author a1294121
 */
public class Visao extends javax.swing.JFrame {

    private HibernateDao hibernatedao = new HibernateDao();

    /**
     * Creates new form Visao
     */
    public Visao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Cliente = new javax.swing.JMenu();
        jMenuItemClienteCadastrar = new javax.swing.JMenuItem();
        jMenuItemClienteAlterar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2Produto = new javax.swing.JMenu();
        jMenuItemProdutoCadastro = new javax.swing.JMenuItem();
        jMenuItemProdutoAlterar = new javax.swing.JMenuItem();
        jMenu6Creditar = new javax.swing.JMenu();
        jMenu7Debitar = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenu2Sobre = new javax.swing.JMenu();
        jMenu1Ajuda = new javax.swing.JMenu();

        jButton3.setText("jButton3");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartão Universitário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341100_shopping_cart.png"))); // NOI18N
        jButton1.setToolTipText("Debitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341006_client.png"))); // NOI18N
        jToggleButton1.setToolTipText("Cadatrar Cliente");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/dinheiro2.png"))); // NOI18N
        jToggleButton2.setToolTipText("Creditar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/a1.jpg"))); // NOI18N

        jButton2.setText("Preencher o banco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 50, Short.MAX_VALUE)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );

        jButton4.setText("jButton4");

        jMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusGained(evt);
            }
        });

        jMenu1Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341006_client.png"))); // NOI18N
        jMenu1Cliente.setToolTipText("Cliente");

        jMenuItemClienteCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980201_executive.png"))); // NOI18N
        jMenuItemClienteCadastrar.setText("Cliente");
        jMenuItemClienteCadastrar.setToolTipText("Cadastrar Cliente");
        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastrarActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteCadastrar);

        jMenuItemClienteAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemClienteAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341694_search_magnifying_glass_find.png"))); // NOI18N
        jMenuItemClienteAlterar.setText("Localizar");
        jMenuItemClienteAlterar.setToolTipText("Localizar Cliente");
        jMenuItemClienteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteAlterarActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItemClienteAlterar);

        jMenuBar1.add(jMenu1Cliente);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1380342968_category_item.png"))); // NOI18N
        jMenu2.setToolTipText("Categoria");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1380342950_category_item.png"))); // NOI18N
        jMenuItem2.setText("Categoria");
        jMenuItem2.setToolTipText("Cadastrar Categoria");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375980081_find.png"))); // NOI18N
        jMenuItem4.setText("Localizar");
        jMenuItem4.setToolTipText("Localizar Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu2Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/product.png"))); // NOI18N
        jMenu2Produto.setToolTipText("Produto");

        jMenuItemProdutoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1375981249_product.png"))); // NOI18N
        jMenuItemProdutoCadastro.setText("Cadastrar");
        jMenuItemProdutoCadastro.setToolTipText("Cadastrar Produto");
        jMenuItemProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoCadastroActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoCadastro);

        jMenuItemProdutoAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemProdutoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341694_search_magnifying_glass_find.png"))); // NOI18N
        jMenuItemProdutoAlterar.setText("Localizar");
        jMenuItemProdutoAlterar.setToolTipText("Localizar Produto");
        jMenuItemProdutoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoAlterarActionPerformed(evt);
            }
        });
        jMenu2Produto.add(jMenuItemProdutoAlterar);

        jMenuBar1.add(jMenu2Produto);

        jMenu6Creditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/dinheiro2.png"))); // NOI18N
        jMenu6Creditar.setToolTipText("Creditar");
        jMenu6Creditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6CreditarMouseClicked(evt);
            }
        });
        jMenu6Creditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6CreditarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6Creditar);

        jMenu7Debitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1373341100_shopping_cart.png"))); // NOI18N
        jMenu7Debitar.setToolTipText("Debitar");
        jMenu7Debitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7DebitarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7Debitar);

        jMenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/relatorio.png"))); // NOI18N
        jMenuRelatorio.setToolTipText("Relatório de produtos em falta");
        jMenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRelatorioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRelatorio);

        jMenu2Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1380342675_Information.png"))); // NOI18N
        jMenu2Sobre.setToolTipText("Sobre");
        jMenu2Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2SobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2Sobre);

        jMenu1Ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/siteajuda.png"))); // NOI18N
        jMenu1Ajuda.setToolTipText("Ajuda");
        jMenu1Ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1AjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1Ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        DebitarRefeicao dr = new DebitarRefeicao();
        dr.setVisible(true);
        dr.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        Cliente c = new Cliente(this);
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new Credito(this).setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jMenuItemClienteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteAlterarActionPerformed
        this.setEnabled(false);
        try {
            new NewConsulta(this, null).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemClienteAlterarActionPerformed

    private void jMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1FocusGained

    private void jMenuBar1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1FocusLost

    private void jMenuItemClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastrarActionPerformed
        this.setEnabled(false);
        Cliente c = new Cliente(this);
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemClienteCadastrarActionPerformed

    private void jMenu1AjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1AjudaMouseClicked
        Desktop desktop = null;
        desktop = Desktop.getDesktop();
        URI uri = null;
        try {
            String local = System.getProperty("user.dir");
            //uri = new URI("C:\\Users\\willian\\Desktop\\Grupo3\\Projeto\\Site");
            uri = new URI(local + "/Site/Help.xhtml");
            desktop.browse(uri);
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (URISyntaxException use) {
            use.printStackTrace();
        }
    }//GEN-LAST:event_jMenu1AjudaMouseClicked

    private void jMenu2SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2SobreMouseClicked
        this.setEnabled(false);
        Sobre w = new Sobre();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu2SobreMouseClicked

    private void jMenu6CreditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6CreditarMouseClicked
        this.setEnabled(false);
        Credito s = new Credito();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenu6CreditarMouseClicked

    private void jMenu7DebitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7DebitarMouseClicked
        this.setEnabled(false);
        DebitarRefeicao dr = new DebitarRefeicao();
        dr.setVisible(true);
        dr.setLocationRelativeTo(null);

    }//GEN-LAST:event_jMenu7DebitarMouseClicked

    private void jMenuItemProdutoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoAlterarActionPerformed
        this.setEnabled(false);
        AtualizarProduto a = null;
        try {
            a = new AtualizarProduto(this);
        } catch (Exception ex) {
            Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemProdutoAlterarActionPerformed

    private void jMenuItemProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoCadastroActionPerformed
        this.setEnabled(false);
        CadastroProduto l = new CadastroProduto(this);
        l.setVisible(true);
        l.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemProdutoCadastroActionPerformed

    private void jMenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRelatorioMouseClicked
        try {
            // obtem o arquivo de relatorio compilado
            URL arquivo = getClass().getResource("relatorio.jasper");

            // carrega o relatorio
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(arquivo);

            // preenche o relatorio com os dados do BD


            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, new HashMap(), DBConnection.getConnection());

            // cria visualizador de relatorio
            JasperViewer jrviewer = new JasperViewer(jasperPrint, false);

            // adicionar visualizador ao frame
            JFrameReport frame = new JFrameReport();
            // adicionamos o visualizador a um JPanel dentro do JFrame
            frame.getjPanelReport().add(jrviewer.getContentPane());
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setVisible(true);


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO: " + e);
        }


    }//GEN-LAST:event_jMenuRelatorioMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.setEnabled(false);
        CategoriaManager a = null;
        try {
            a = new CategoriaManager(this);
        } catch (Exception ex) {
            Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
        }
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu6CreditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6CreditarActionPerformed
        this.setEnabled(false);
        new Credito(this).setEnabled(true);
    }//GEN-LAST:event_jMenu6CreditarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            preencherBanco();
        } catch (Exception ex) {
            Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    private void preencherBanco() throws Exception{
        HibernateDao hb = new HibernateDao();
            Categoria c = new Categoria();
        DaoCategoria dc = new DaoCategoria();
        for (int i = 0; i < 3; i++) {
             c = new Categoria();
            c.setCargo("Categoria" + i);
            c.setRefeicao(i);
            try {
                dc.persist(c);
            } catch (Exception ex) {
                Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        for (int i = 0; i < 3; i++) {
            Pessoa p = new Pessoa();
            p.setNome("Pessoa" + i);
            p.setCategoria(c);
            p.setEmail("Email" + i + "@email.com");
            p.setCodigo(i);
            p.setSaldo(10);
            try {
                hb.persist(p);
            } catch (Exception ex) {
                Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        for (int i = 0; i < 3; i++) {
            Produto pr = new Produto();
            pr.setNome("Produto" + i);
            pr.setPrecoCusto(1.0f);
            pr.setPrecoVenda(2.0f);
            pr.setEspecificacoes("Produto" + i);
            pr.setHabilitadoVendas(true);
            try {
                hb.persist(pr);
            } catch (Exception ex) {
                Logger.getLogger(Visao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Visao v = new Visao();
//                v.setVisible(true);
//                v.setLocationRelativeTo(null);
                new Visao().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1Ajuda;
    private javax.swing.JMenu jMenu1Cliente;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu2Produto;
    private javax.swing.JMenu jMenu2Sobre;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6Creditar;
    private javax.swing.JMenu jMenu7Debitar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemClienteAlterar;
    private javax.swing.JMenuItem jMenuItemClienteCadastrar;
    private javax.swing.JMenuItem jMenuItemProdutoAlterar;
    private javax.swing.JMenuItem jMenuItemProdutoCadastro;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
